Mq/mongo capped
softwaremill/mqperf pull request #10
Opened 2016-12-23 13:13 UTC by mkubala

A simple Mongo capped collection & tailable cursor based queue.

This is still a **WIP**, tasks left to do:

- [ ] prepare different test configurations
- [ ] introduce node-scoped cursor state (right now all nodes use the same 'last seen doc' property)

2016-12-27 08:06 UTC, kciesielski commented
Looks good :) The only thing that concerns me is the Option allocation, could you compare if it affects results in any significant way?

2016-12-29 08:56 UTC, mkubala commented
Will check 👍

2016-12-30 10:49 UTC, kciesielski requested changes

2016-12-30 10:49 UTC, kciesielski commented on src/main/scala/com/softwaremill/mqperf/mq/MongoCappedMq.scala
> +        Option(cursor.tryNext()) match {
If we are processing hundreds of thousands msgs per second then maybe it's better to avoid this allocation and use a dirty nullcheck instead.

2016-12-30 10:49 UTC, kciesielski commented on src/main/scala/com/softwaremill/mqperf/mq/MongoCappedMq.scala
> +      Future {
Shouldn't we use a separate thread pool here? The `global` may get saturated if we ack fast which may block other activities.

2016-12-30 10:50 UTC, mkubala commented on src/main/scala/com/softwaremill/mqperf/mq/MongoCappedMq.scala
> +      Future {
👍 good idea

2016-12-30 12:10 UTC, kciesielski approved these changes

2016-12-30 12:10 UTC, merged