Add S3 bucket variables
softwaremill/mqperf pull request #71
Opened 2022-08-16 14:48 UTC by hubertklusek

2022-08-17 12:08 UTC, abielawa approved these changes

2022-08-17 12:21 UTC, Sztigar requested changes

2022-08-17 12:21 UTC, Sztigar commented on live/terragrunt.hcl
> +    bucket         = TF_VAR_BUCKET_NAME
I think we need to use built-in function `get_env(NAME)` here, like this `get_env("TF_VAR_BUCKET_NAME")`

2022-08-17 12:21 UTC, Sztigar commented on live/terragrunt.hcl
> +    region         = TF_VAR_AWS_REGION
Same as above,  shouldn't we do this `get_env("TF_VAR_AWS_REGION")`?

2022-08-18 11:05 UTC, gkocur requested changes

2022-08-18 11:05 UTC, gkocur commented on live/terragrunt.hcl
> +    dynamodb_table = "terraform-locks"
Why not get the dynamo-db table name also from env?

2022-08-18 11:49 UTC, closed without merging