add nodepools config variables
softwaremill/mqperf pull request #94
Opened 2022-10-19 06:20 UTC by hubertklusek

2022-10-19 07:10 UTC, gkocur requested changes

2022-10-19 07:10 UTC, gkocur commented on terraform/example-data.json
> -        "nodes_number": "3",
It's a max number of nodes? So maybe `max_nodes_number`?

2022-10-19 07:10 UTC, gkocur commented on terraform/example-data.json
> +        "app_nodes_number": "1",
same as above

2022-10-19 07:10 UTC, gkocur commented on terraform/live/_envcommon/eks.hcl
>        desired_size   = 1
For EKS it's more complicated. It doesn't scale in the same way as GKE, so probably we want to set desired_size same as max_size.

2022-10-19 07:10 UTC, gkocur commented on terraform/live/_envcommon/gke.hcl
>        preemptible  = true
Using preemtible nodes is a good idea, but in some cases not desirable. I'd make it configurable.

2022-10-19 10:40 UTC, hubertklusek commented on terraform/live/_envcommon/eks.hcl
>        desired_size   = 1
done

2022-10-19 16:23 UTC, hubertklusek commented on terraform/example-data.json
> -        "nodes_number": "3",
done

2022-10-20 09:00 UTC, gkocur approved these changes

2022-10-20 09:08 UTC, merged